### ISSUE TITLE
(dark/light) Solarized: follow system theme

### ISSUE THREAD

**Issue by khonkhortisan** [AnKingMed/AnkiRecolor#15]
#### Checklist

 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
        - this deleted extra .json themes I saved from the wiki
 - [x] I've checked if anyone else suggested this feature before by looking through the issue reports.

#### What Anki version are you using?

```
2.1.54
```

#### Problem case

Setting Anki to light mode, ReColor to (light) Solarized, Anki to dark mode, doesn't use (dark) Solarized's Window Background color behind the card while reviewing.

#### Solution

*Concisely describe the solution you would like*
When Anki is set to light mode, match the colors of (light) Solarized; when Anki is set to dark mode, match the colors of (dark) Solarized.
I realize there may be a technical issue because it's not as simple as Nord, there may need to be a dark theme and a light theme set separately in ReColor (which opens up the possibility for them being different themes), and an extra hook to apply the other theme whenever the Anki's dark mode is toggled by following the system.

*Concisely describe alternatives you've considered (if any)*
Anki theme, Nord theme, manually changing the theme when the sun goes up/down

#### More information

*Additional context: Add any other context or screenshots about the feature request here.*

**Comment by BlueGreenMagick** [comment]
You can apply both '(light) Solarized' and '(dark) Solarized', and it should use `(light) Solarized` in light mode and `(dark) Solarized` in dark mode.

I'm keeping the themes separate because it was developed by different authors, and the light mode and dark mode doesn't really look like the same theme.
