### ISSUE TITLE
Weird appearance of buttons

### ISSUE THREAD

**Issue by CNote1** [AnKingMed/AnkiRecolor#20]
#### Checklist

 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've checked if anyone else asked this question before by looking through the issue reports.

#### What Anki version are you using?
```
2.1.55
```

#### Your question
![anki_buttons](https://user-images.githubusercontent.com/37962556/209478600-a4206273-3e09-4927-aa69-ebfa4cf0d30a.png)
Hello!
Is there any way I can style this three white buttons showed in picture using CSS? They are basically all white with whitish text inside them. Text is only visible when I hover over button:
![anki_button_2](https://user-images.githubusercontent.com/37962556/209478703-091ddca6-1604-4cba-bc94-9c99451e0175.png)

**Comment by BlueGreenMagick** [comment]
#[3795f97](https://github.com/AnKingMed/AnkiRecolor/commit/3795f976f2abff52d8e382cafe302bd795297d31) fixes this issue
